pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Clean') {
            steps {
                bat 'mvn clean'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

                stage('Publish Extent Report') {
                    steps {
                        publishHTML(target: [
                            allowMissing: false,
                            alwaysLinkToLastBuild: true,
                            keepAll: true,
                            reportDir: 'target/extent_report',
                            reportFiles: 'ExtentReport.html',
                            reportName: 'Extent Report'
                        ])
                    }
                }
            }

 post {

     always {
         archiveArtifacts artifacts: 'target/**/*', allowEmptyArchive: true
     }

     success {

         emailext(

             subject: "✅ ${env.JOB_NAME} | SUCCESS | Build #${env.BUILD_NUMBER}",

             mimeType: 'text/html',

             to: 'dhanush.testing100@gmail.com',

             body: """
             <html>

             <body style="font-family:Arial;">

             <h2 style="color:green;">
             Automation Execution Successful
             </h2>

             <table border="1"
                    cellpadding="8"
                    cellspacing="0"
                    style="border-collapse:collapse;">

                 <tr bgcolor="#DFF0D8">
                     <th>Property</th>
                     <th>Value</th>
                 </tr>

                 <tr>
                     <td><b>Project</b></td>
                     <td>${env.JOB_NAME}</td>
                 </tr>

                 <tr>
                     <td><b>Build Number</b></td>
                     <td>#${env.BUILD_NUMBER}</td>
                 </tr>

                 <tr>
                     <td><b>Status</b></td>
                     <td style="color:green;"><b>SUCCESS</b></td>
                 </tr>

                 <tr>
                     <td><b>Build URL</b></td>
                     <td>
                     <a href="${env.BUILD_URL}">
                     ${env.BUILD_URL}
                     </a>
                     </td>
                 </tr>

             </table>

             <br>

             <h3>Attachments</h3>

             <ul>
                 <li>Extent Report</li>
             </ul>

             <br>

             <i>
             This is an automated email generated by Jenkins.
             </i>

             </body>

             </html>
             """,

             attachmentsPattern: 'target/extent_report/ExtentReport.html'

         )
     }

     failure {

         emailext(

             subject: "❌ ${env.JOB_NAME} | FAILED | Build #${env.BUILD_NUMBER}",

             mimeType: 'text/html',

             to: 'dhanush.testing100@gmail.com',

             body: """
             <html>

             <body style="font-family:Arial;">

             <h2 style="color:red;">
             Automation Execution Failed
             </h2>

             <table border="1"
                    cellpadding="8"
                    cellspacing="0"
                    style="border-collapse:collapse;">

                 <tr bgcolor="#F2DEDE">
                     <th>Property</th>
                     <th>Value</th>
                 </tr>

                 <tr>
                     <td><b>Project</b></td>
                     <td>${env.JOB_NAME}</td>
                 </tr>

                 <tr>
                     <td><b>Build Number</b></td>
                     <td>#${env.BUILD_NUMBER}</td>
                 </tr>

                 <tr>
                     <td><b>Status</b></td>
                     <td style="color:red;"><b>FAILED</b></td>
                 </tr>

                 <tr>
                     <td><b>Build URL</b></td>
                     <td>
                     <a href="${env.BUILD_URL}">
                     ${env.BUILD_URL}
                     </a>
                     </td>
                 </tr>

             </table>

             <br>

             <h3>Attachments</h3>

             <ul>
                 <li>Extent Report</li>
             </ul>

             <br>

             <i>
             Please check the attached report.
             </i>

             </body>

             </html>
             """,

             attachmentsPattern: 'target/extent_report/ExtentReport.html'
         )
     }

 }
